name: Safaa Model retraining

on:
#  push:
#    branches: [testing]
#  pull_request:
#    branches: [testing]
  workflow_dispatch:

jobs:
  safaa-model-retraining:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: utility/retraining
#      SAFAA_SECRET: ${{ secrets.MY_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set PYTHONPATH for future steps
        run: echo "PYTHONPATH=$(pwd)/Safaa/src" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r $BASE_PATH/requirements.txt
#      - name: Create .env file
#        run: |
#          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
#          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
#          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
#          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

#      - name: Fetch Copyright content from server
#        run: |
#          python $BASE_PATH/script_for_copyrights.py

      - name: Run utility script (preprocess, declutter, split)
        run: |
          export PYTHONPATH=$(pwd)/Safaa/src
          python $BASE_PATH/utility_scripts.py
      - name: Show final output files (for confirmation/logging)
        run: |
          ls -lh $BASE_PATH/data/