name: Safaa Model retraining

on:
#  push:
#    branches: [testing]
#  pull_request:
#    branches: [testing]
  workflow_dispatch:

jobs:
  safaa-model-retraining:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: utility/retraining
      PYTHONPATH: ${{ github.workspace }}/Safaa/src
#      SAFAA_SECRET: ${{ secrets.MY_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install "spacy~=3.8.7" \
                      "pandas~=2.2.3" \
                      "psycopg2~=2.9.10" \
                      "python-dotenv~=1.1.0" \
                      "scikit-learn~=1.7.0"

#      - name: Create .env file
#        run: |
#          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
#          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
#          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
#          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

#      - name: Fetch Copyright content from server
#        run: |
#          python $BASE_PATH/script_for_copyrights.py

      - name: Run utility steps
        run: |
          python $BASE_PATH/utility_scripts.py --preprocess
          python $BASE_PATH/utility_scripts.py --declutter
          python $BASE_PATH/utility_scripts.py --split
          python $BASE_PATH/utility_scripts.py --train
          python $BASE_PATH/utility_scripts.py --train

      - name: Show final output files (for confirmation/logging)
        run: |
          ls -lh $BASE_PATH/data/
          ls -lh $BASE_PATH/model/